# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 716c76b0a00818454dab78261b44b3fdf00b421b84044aac8997776675c3f2bb04166f5d8ca42505e69d05a32b24f9df61d172f832f83d2631e081d3db3b92ca

test:
  secret_key_base: 1989d34a506722cfe61482338bf2b8656e3b80da92f4aafe8e7aa79760f40b65acd56f0f47c85edd4767ef8d06e908552d22d4581ef1c7b6a03edd6177904aea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
